name: Update Profile Daily

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Generate SVG
        run: python generate_svg.py
        env:
          GH_KEY: ${{ secrets.GH_KEY }}

      - name: Commit and Push if Changed
        run: |
          CURRENT_DATE=$(date +'%d/%m/%y')
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GH_KEY }}@github.com/${{ github.repository }}
          git fetch origin main
          git reset --hard origin/main
          python generate_svg.py
          git add profile.svg
          git diff --cached --quiet || git commit -m "Update Profile - ${CURRENT_DATE}"
          git push
        env:
          GH_KEY: ${{ secrets.GH_KEY }}
